--[[

	BWhitelist Portuguese
  
	Contributors:
  
	Pedro - STEAM_0:0:150648784
  
]]

BWhitelist.Language = {
	permission_failure = "Actualmente no tiene permiso para hacerlo.",
	disabled_whitelist = "La lista blanca para este trabajo está deshabilitada.",
	no_whitelist_permission = "No tienes permiso para editar esta lista blanca.",
	search_jobs = "Buscar trabajos...",
	steamid_finder = "Buscar STEAM ID",
	type = "Tipo",
	value = "Valor",
	team_name = "Nombre",
	select_job = "Seleccione un trabajo a la izquierda...",
	enable_whitelist = "Habilitar lista blanca?",
	enabling_whitelist = "Habilitación de la lista blanca...",
	add_to_whitelist = "Añadir a la lista blanca",
	disable_whitelist = "Desactivar lista blanca",
	clear_whitelist = "Borrar lista blanca",
	search = "Buscar...",
	no_data = "Sin datos!",
	retrieving = "Recuperando...",
	admin_mode = "Modo de administración",
	admin_tab = "Administración",
	jobs_tab = "Trabajos",
	players_tab = "Jugadores",
	default_team = "Éste es el equipo predeterminado. No puedes incluir en la lista blanca el equipo predeterminado..",
	remove_from_whitelist = "Eliminar de la lista blanca",
	player_name = "Nombre",
	remove_from_whitelist_selected_tooltip = "Eliminar el usuario seleccionado de una lista blanca",
	add_to_whitelist_selected_tooltip = "Agregar el usuario seleccionado a una lista blanca",
	clear_whitelist_tooltip = "[Administración]Limpia la lista blanca. Todos los identificadores de Steam y grupos de usuarios se eliminan.",
	disable_whitelist_tooltip = "Desactiva la lista blanca. Los jugadores pueden unirse libremente al trabajo.",
	add_to_whitelist_tooltip = "Agrega un Steam ID, SteamID64 o grupo de usuarios a la lista blanca para este trabajo.",
	remove_from_whitelist_tooltip = "Elimina SteamID, SteamID64 o grupo de usuarios de la lista blanca para este trabajo.",
	in_jobs_file_tooltip = "No puedes deshabilitar esta lista blanca porque es BWhitelist activada en tu archivo de trabajos DarkRP.",
	add_steamid = "Añadir SteamID/64",
	add_usergroup = "Añadir Usergroup",
	add_usergroup_modal = "Escriba el grupo de usuarios que desea agregar a continuación.",
	add_steamid_modal = "Pegue el SteamID / SteamID64 que desea agregar a continuación. Recuerde que hay una manera más fácil de hacerlo, vaya a la pestaña \"Jugadores\" en el menú!",
	error = "errores",
	not_a_steamid_or_64 = "Eso no es un SteamID o SteamID64!",
	already_exists = "Eso ya existe en la lista blanca!",
	doesnt_exist = "Eso no existe en la lista blanca!",
	copy = "Dupdo",
	copy_tooltip = "Copia el grupo de usuarios seleccionado o SteamID.",
	player_left = "Lo sentimos, parece que ese jugador ha dejado el servidor.",
	no_enabled_whitelists = "¡No hay listas blancas habilitadas a las que tenga acceso!",
	import_from_mayoz = "Importación del sistema de listas blancas de Mayoz",
	import_from_nordahl = "Importación del sistema de listas blancas de Nordahl",
	import_from_old_bwhitelist = "Importar de la antigua lista blanca de B",
	view = "Ver",
	no_import = "Parece que no pudimos encontrar los archivos / los archivos están dañados que se requieren para importar.",
	import_from_old_bwhitelist_tooltip = "Si podemos encontrar cualquiera de los antiguos archivos de la lista blanca en su servidor, los convertiremos en los nuevos archivos.",
	import_from_mayoz_tooltip = "Si podemos encontrar cualquiera de los archivos del lista blanca System del alcalde en su servidor, los convertiremos en archivos de la lista blanca B.",
	import_from_nordahl_tooltip = "Si podemos encontrar cualquiera de los archivos del sistema lista blanca de Nordahl en su servidor, los convertiremos en archivos de lista blanca.",
	disable_all_whitelists = "Todos los trabajos tendrán sus listas blancas deshabilitadas. Todos los datos permanecerán.",
	enable_all_whitelists = "Todos los trabajos tendrán sus listas blancas habilitadas.",
	steamprofile = "Steam Perfil",
	confirm = "Confirmar",
	are_you_sure = "¿Seguro que quieres hacer esto?",
	yes = "Sí",
	cancel = "Cancelar",
	reset_everything = "Restablecer todo",
	reset_everything_tooltip = "ADVERTENCIA: Esto eliminará TODOS los datos de la lista blanca y las listas blancas habilitadas..",
	go = "Ir",
	customcheck_team = "Este equipo tiene un CustomCheck en él. Esto reemplaza a la lista blanca B.Por favor, cambie \"customCheck\" a \"BWhitelist_customCheck \ en su archivo de trabajos para que su customCheck trabaje con B Whitelist.",
	removed_from_whitelist = "Has sido eliminado de la lista blanca para",
	added_to_whitelist = "Has sido añadido a la lista blanca para",
	disable_all_whitelists = "Desactivar todas las listas blancas",
	enable_all_whitelists = "Habilitar todas las listas blancas",
	player_left = "El jugador ha dejado.",
	no_actions_available = "No hay acciones disponibles para este jugador.",
	remove_from_all_whitelists = "Eliminar de todas las listas blancas",
	add_to_all_whitelists = "Añadir a todas las listas blancas",
	clear_unknown_jobs = "Borrar trabajos desconocidos",
	clear_unknown_jobs_tooltip = "Si hay datos de lista blanca en la base de datos relacionados con un trabajo que ya no existe, todo se borrará con este botón. Los datos de la lista blanca de ese trabajo se mantendrán en caso de que lo necesite en el futuro.",
}
