--[[

	BWhitelist Portuguese
  
	Contributors:
  
	Pedro - STEAM_0:0:150648784
  
]]

BWhitelist.Language = {
	permission_failure = "Atualmente, você não tem permissão para fazer isso.",
	disabled_whitelist = "A lista branca para este trabalho está desativada.",
	no_whitelist_permission = "Você não tem permissão para editar esta lista branca.",
	search_jobs = "Procurar empregos...",
	steamid_finder = "SteamID Pesquisa",
	type = "Tipo",
	value = "Valor",
	team_name = "Nome",
	select_job = "Selecione um trabalho à esquerda...",
	enable_whitelist = "Ativar lista branca?",
	enabling_whitelist = "Permitir a lista branca...",
	add_to_whitelist = "Adicionar à Lista Branca",
	disable_whitelist = "Desativart Lista Branca",
	clear_whitelist = "Clearlist claro",
	search = "Pesquisa...",
	no_data = "Sem dados!",
	retrieving = "Recuperando...",
	admin_mode = "Modo Administrador",
	admin_tab = "Administrador",
	jobs_tab = "Empregos",
	players_tab = "Jogadoras",
	default_team = "Esta é a equipe padrão. Você não pode lista branca da equipe padrão.",
	remove_from_whitelist = "Remover da lista branca",
	player_name = "Nome",
	remove_from_whitelist_selected_tooltip = "Remova o usuário selecionado de uma lista branca",
	add_to_whitelist_selected_tooltip = "Adicione o usuário selecionado a uma lista branca",
	clear_whitelist_tooltip = "[Administrador only] Limpa a lista branca. Todos os SteamIDs e grupos de usuários são removidos.",
	disable_whitelist_tooltip = "Desativa a lista branca. Os jogadores podem participar do trabalho livremente.",
	add_to_whitelist_tooltip = "Adiciona Steam ID, SteamID64 ou grupo de usuários à lista branca para este trabalho.",
	remove_from_whitelist_tooltip = "Remove o SteamID selecionado, SteamID64 ou grupo de usuários da lista branca para este trabalho.",
	in_jobs_file_tooltip = "Você não pode desativar esta lista branca porque é BWhitelist habilitado no seu arquivo de tarefas DarkRP.",
	add_steamid = "Adicionar SteamID/64",
	add_usergroup = "Adicionar Usergroup",
	add_usergroup_modal = "Digite o grupo de usuários que deseja adicionar abaixo.",
	add_steamid_modal = "Cole o SteamID/SteamID64 você quer adicionar abaixo. Lembre-se de que existe uma maneira mais fácil de fazer isso, vá para o \"Jogador\" tab no menu!",
	error = "Erro,
	not_a_steamid_or_64 = "Isso não é um SteamID ou SteamID64!",
	already_exists = "Isso já existe na lista branca!",
	doesnt_exist = "Isso não existe na lista branca!",
	copy = "cópia de",
	copy_tooltip = "Copia o grupo de usuários selecionado ou SteamID.",
	player_left = "Desculpe, parece que o jogador deixou o servidor.",
	no_enabled_whitelists = "Não há listas brancas habilitadas para as quais você tenha acesso!",
	import_from_mayoz = "Importação do Sistema de Lista Branca de Mayoz",
	import_from_nordahl = "Importação do Sistema de Lista Branca de Nordahl ",
	import_from_old_bwhitelist = "Importar da lista branca antiga B",
	view = "Visão",
	no_import = "Parece que não conseguimos encontrar os arquivos / os arquivos estão corrompidos e que são necessários para importar.",
	import_from_old_bwhitelist_tooltip = "Se pudermos encontrar qualquer um dos velhos arquivos da Lista B em seu servidor, os converteremos nos novos arquivos.",
	import_from_mayoz_tooltip = "Se pudermos encontrar qualquer um dos arquivos do Sistema de listas brancas do Prefeito no seu servidor, os converteremos em arquivos da Lista Branca B.",
	import_from_nordahl_tooltip = "If we can find any of Nordahl's Whitelist System files on your server, we'll convert them into B Whitelist files.",
	disable_all_whitelists = "Todos os trabalhos terão suas listas brancas desabilitadas. Todos os dados permanecerão.",
	enable_all_whitelists = "odos os trabalhos terão suas listas brancas habilitadas.",
	steamprofile = "Steam Perfil",
	confirm = "Confirme",
	are_you_sure = "Você tem certeza de que quer fazer isso?",
	yes = "Sim",
	cancel = "Cancelar",
	reset_everything = "Repor tudo",
	reset_everything_tooltip = "AVISO: isso eliminará TODOS os dados da lista branca e habilitará as listas brancas.",
	go = "Ie",
	customcheck_team = "Este time tem um customCheck sobre ele. Isso substitui a Lista Branca B. Por favor, mude \"customCheck\" to \"BWhitelist_customCheck\"no seu arquivo de tarefas para o seu customCheck para trabalhar com a Lista Branca B.",
	removed_from_whitelist = "Você foi removido da lista branca para \"%s\"",
	added_to_whitelist = "Você foi adicionado à lista branca para \"%s\"",
	disable_all_whitelists = "Desativar todas as listas brancas",
	enable_all_whitelists = "Habilitar todas as listas brancas",
	player_left = "O jogador deixou.",
	no_actions_available = "Nenhuma ação disponível para este jogador.",
	remove_from_all_whitelists = "Remover de todas as listas brancas",
	add_to_all_whitelists = "Adicione a todas as listas brancas",
	clear_unknown_jobs = "Limpar trabalhos desconhecidos ",
	clear_unknown_jobs_tooltip = "Se houver dados da lista branca no banco de dados relacionados a um trabalho que não existe mais, todos serão excluídos com este botão. Os dados da lista branca desse trabalho serão mantidos no caso de você precisar no futuro.",
}
